!what is the purpose of this??? JM Feb 26 08



!$OMP THREADPRIVATE(pftflag)
!$OMP THREADPRIVATE(pftpar)

!$OMP THREADPRIVATE(lat)

!$OMP THREADPRIVATE(mtemp)
!$OMP THREADPRIVATE(mpred)
!$OMP THREADPRIVATE(msun)
!$OMP THREADPRIVATE(mshortrad)
!$OMP THREADPRIVATE(mlongrad)

!$OMP THREADPRIVATE(soilcode)
!$OMP THREADPRIVATE(soilparm)

!$OMP THREADPRIVATE(co2)

!$OMP THREADPRIVATE(soilpar)
!$OMP THREADPRIVATE(whcmm)
!$OMP THREADPRIVATE(kmmd)

!$OMP THREADPRIVATE(acflux_estab)
!$OMP THREADPRIVATE(acflux_fire)
!$OMP THREADPRIVATE(arh)

!$OMP THREADPRIVATE(cpool_fast)
!$OMP THREADPRIVATE(cpool_slow)
!$OMP THREADPRIVATE(litter_decom_ave)

!$OMP THREADPRIVATE(arunoff)
!$OMP THREADPRIVATE(arunoff_drain)
!$OMP THREADPRIVATE(arunoff_surf)
!$OMP THREADPRIVATE(afire_frac)
!$OMP THREADPRIVATE(aaet)

!$OMP THREADPRIVATE(gdd_buf)
!$OMP THREADPRIVATE(mtemp_min_buf)

!$OMP THREADPRIVATE(cosinelat)
!$OMP THREADPRIVATE(gdd)
!$OMP THREADPRIVATE(gdd20)
!$OMP THREADPRIVATE(k_fast_ave)
!$OMP THREADPRIVATE(k_slow_ave)
!$OMP THREADPRIVATE(mtemp_max)
!$OMP THREADPRIVATE(mtemp_min20)
!$OMP THREADPRIVATE(sinelat)

!$OMP THREADPRIVATE(stemp)

!$OMP THREADPRIVATE(w)

!$OMP THREADPRIVATE(dmelt)
!$OMP THREADPRIVATE(dpet)
!$OMP THREADPRIVATE(dprec)
!$OMP THREADPRIVATE(dshortrad)
!$OMP THREADPRIVATE(dlongrad)
!$OMP THREADPRIVATE(dtemp)
!$OMP THREADPRIVATE(dtemp_soil)
!$OMP THREADPRIVATE(dw1)
!$OMP THREADPRIVATE(snowpack)

!$OMP THREADPRIVATE(dwscal365)
!$OMP THREADPRIVATE(crownarea)
!$OMP THREADPRIVATE(fpc_grid)
!$OMP THREADPRIVATE(fpc_inc)
!$OMP THREADPRIVATE(height)
!$OMP THREADPRIVATE(lai_ind)
!$OMP THREADPRIVATE(nind)
!$OMP THREADPRIVATE(sla)
!$OMP THREADPRIVATE(turnover_ind)
!$OMP THREADPRIVATE(heatstress)

!$OMP THREADPRIVATE(litter_ag_fast)
!$OMP THREADPRIVATE(litter_ag_slow)
!$OMP THREADPRIVATE(litter_bg)
!$OMP THREADPRIVATE(lm_ind)
!$OMP THREADPRIVATE(lm_sapl)
!$OMP THREADPRIVATE(rm_ind)
!$OMP THREADPRIVATE(rm_sapl)
!$OMP THREADPRIVATE(sm_ind)
!$OMP THREADPRIVATE(sm_sapl)
!$OMP THREADPRIVATE(hm_ind)
!$OMP THREADPRIVATE(hm_sapl)
!$OMP THREADPRIVATE(bm_inc)
!$OMP THREADPRIVATE(agpp)
!$OMP THREADPRIVATE(alresp)
!$OMP THREADPRIVATE(anpp)

!$OMP THREADPRIVATE(dnpp)
!$OMP THREADPRIVATE(npp_buf)

!$OMP THREADPRIVATE(leafondays)
!$OMP THREADPRIVATE(leafoffdays)

!$OMP THREADPRIVATE(leafon)

!$OMP THREADPRIVATE(wscal)

!$OMP THREADPRIVATE(dphen)
!$OMP THREADPRIVATE(dphen_t)
!$OMP THREADPRIVATE(dphen_w)

!$OMP THREADPRIVATE(mdayl)
!$OMP THREADPRIVATE(mpar_day)
!$OMP THREADPRIVATE(mrunoff)
!$OMP THREADPRIVATE(mtemp_old)
!$OMP THREADPRIVATE(mtemp_soil)
!$OMP THREADPRIVATE(mw1)
!$OMP THREADPRIVATE(u)
!$OMP THREADPRIVATE(v)
!$OMP THREADPRIVATE(sinehh)
!$OMP THREADPRIVATE(hh)
!$OMP THREADPRIVATE(qo)
!$OMP THREADPRIVATE(mpet)

!$OMP THREADPRIVATE(mrh)
!$OMP THREADPRIVATE(dmrh)
!$OMP THREADPRIVATE(dmw1)
!$OMP THREADPRIVATE(droff)

!$OMP THREADPRIVATE(mgpp)
!$OMP THREADPRIVATE(mlresp)
!$OMP THREADPRIVATE(mnpp)

!$OMP THREADPRIVATE(m)
!$OMP THREADPRIVATE(c)

!$OMP THREADPRIVATE(year)
!$OMP THREADPRIVATE(radiation)
!$OMP THREADPRIVATE(dogridcell)
!$OMP THREADPRIVATE(doyear)

